name: Set CNAME

on: create

permissions:
  contents: write

jobs:
  set-cname:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ github.repository_owner }}.githubpage" > CNAME
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add CNAME
          git commit -m "Set custom CNAME"
          git push
